# Generated by Django 3.0.8 on 2020-07-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('account', models.CharField(max_length=200)),
                ('information', models.TextField()),
                ('info_created_at', models.DateTimeField(auto_now_add=True)),
                ('info_updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
