# Generated by Django 3.0.8 on 2020-02-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200717_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
